/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GDSViewerDialog.java
 *
 * Created on Jul 2, 2010, 2:22:37 PM
 */

package org.genmapp.expressionreader.ui;

/**
 *
 * @author djiao
 */
public class GDSViewerDialog extends javax.swing.JDialog {

    /** Creates new form GDSViewerDialog */
    public GDSViewerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        sOFTViewerPane1 = new org.genmapp.expressionreader.ui.SOFTViewerPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSplitPane1.setLeftComponent(sOFTViewerPane1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GDSViewerDialog dialog = new GDSViewerDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private org.genmapp.expressionreader.ui.SOFTViewerPane sOFTViewerPane1;
    // End of variables declaration//GEN-END:variables

}
