/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GEOSearchDialog.java
 *
 * Created on Jul 1, 2010, 5:29:56 PM
 */

package org.genmapp.expressionreader.ui;

import cytoscape.Cytoscape;
import cytoscape.task.Task;
import cytoscape.task.ui.JTaskConfig;
import cytoscape.task.util.TaskManager;
import cytoscape.util.ModulePropertiesImpl;
import gov.nih.nlm.ncbi.soap.eutils.EUtilsService;
import gov.nih.nlm.ncbi.soap.eutils.EUtilsServiceSoap;
import gov.nih.nlm.ncbi.soap.eutils.esearch.ESearchRequest;
import gov.nih.nlm.ncbi.soap.eutils.esearch.ESearchResult;
import javax.swing.SwingUtilities;
import org.genmapp.expressionreader.tasks.AbstractTask;

/**
 *
 * @author djiao
 */
public class GEOSearchDialog extends javax.swing.JDialog {

    /** Creates new form GEOSearchDialog */
    public GEOSearchDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultScrollPane = new javax.swing.JScrollPane();
        resultList = new javax.swing.JList();
        searchPane = new javax.swing.JPanel();
        searchFld = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        bottomPane = new javax.swing.JPanel();
        viewBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        resultScrollPane.setViewportView(resultList);

        getContentPane().add(resultScrollPane, java.awt.BorderLayout.CENTER);

        searchPane.setLayout(new java.awt.BorderLayout());

        searchFld.setMinimumSize(new java.awt.Dimension(150, 27));
        searchPane.add(searchFld, java.awt.BorderLayout.CENTER);

        searchBtn.setText("Search!");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        searchPane.add(searchBtn, java.awt.BorderLayout.LINE_END);

        getContentPane().add(searchPane, java.awt.BorderLayout.PAGE_START);

        viewBtn.setText(" View ");
        bottomPane.add(viewBtn);

        getContentPane().add(bottomPane, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        ESearchRequest request = new ESearchRequest();
        request.setDb("geo");
        request.setRetMax("25");
        request.setTerm(searchFld.getText());

        final ESearchRequest query = request;

        Task task = new AbstractTask() {

            public void run() {
                EUtilsService service = new EUtilsService();
                EUtilsServiceSoap clientStub = service.getEUtilsServiceSoap();
                final ESearchResult result = clientStub.runESearch(query);

                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        // populate result list
                        System.out.println(result.getCount());
                    }
                });
            }

            public String getTitle() {
                return "Search GEO";
            }

        };
        JTaskConfig config = new JTaskConfig();
        config.setModal(false);
        config.setOwner(Cytoscape.getDesktop());
        config.setAutoDispose(true);
        TaskManager.executeTask(task, config);
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GEOSearchDialog dialog = new GEOSearchDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPane;
    private javax.swing.JList resultList;
    private javax.swing.JScrollPane resultScrollPane;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchFld;
    private javax.swing.JPanel searchPane;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables

}
